= openEHR-antlr4

Antlr4 grammars for ADL, ODIN, BEL, EL, BMM.

== Status

This is a development repository containing Antlr4 grammars for most of the languages and syntaxes in use in openEHR. It may be used as a source for grammars for official use in various specifications.

Production grammars for ADL are currently in https://github.com/openEHR/adl-antlr[the adl-antlr repo^].

== What's in the project?

The grammars are maintained under the `combined/src/main/antlr` directory.

A Java test program is in `/combined/src/test/java/org/openehr/adlReader`, and test files in `/combined/src/test/resources` .

== Related Specifications

Relevant specifications may be found on the https://specifications.openehr.org/development_baseline[openEHR specifications home page^], in particular:

* https://specifications.openehr.org/releases/AM/latest[the ADL specifications^]
* the https://specifications.openehr.org/releases/LANG/latest/EL.html[Expression Language (EL) specification^]
* the https://specifications.openehr.org/releases/LANG/latest/BEL.html[Basic Expression Language (BEL) specification^]
